### ISSUE TITLE
http://groovykoans.org/ is no longer accessible as of 5/7/2015

### ISSUE THREAD

**Issue by michaelsalvia** [nadavc/groovykoans#30]
http://groovykoans.org/ is no longer accessible as of 5/7/2015

**Comment by danhyun** [comment]
+1

**Comment by nadavc** [comment]
Yes - this domain business is becoming expensive :) I think I might revert back to http://groovykoans.github.io.

**Comment by michaelsalvia** [comment]
Let me know what you decide! The webpage was a nice landing page. I would offer to host it as well somewhere if you would like!

**Comment by danhyun** [comment]
Perhaps it would be best to use gh-pages then just have a domain point to it?

**Comment by nadavc** [comment]
Thanks guys :+1: ! The landing page already uses gh-pages, so you should be able to use  http://nadavc.github.io/groovykoans to get to the same page. Google is probably the faster option though.

**Comment by danhyun** [comment]
Thanks so much @nadavc !
