### ISSUE TITLE
Prevent opening the File window

### ISSUE THREAD

**Issue by freegenie** [nadavc/groovykoans#31]
Not really an issue but, is there a way to prevent the file window to open (I'm on linux) every time I run a test?

**Comment by nadavc** [comment]
Can you share a screenshot please?

**Comment by freegenie** [comment]
I get this message in case of failures: 

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/fregini/Work/test-groovy/groovykoans/build/reports/tests/index.html

and the URL is opened with the default application for html files.

**Comment by nadavc** [comment]
Gotcha. That was actually by design... simply because it was difficult (for me) to copy and paste the report into a browser. If you want to stop the script from doing that, you can simply remove the two lines starting at https://github.com/nadavc/groovykoans/blob/master/build.gradle#L78.

**Comment by freegenie** [comment]
ok got it thanks.
